INCLUDES += -I$(BINDIR)/include
INCLUDES += -I$(MICRO_ROS_MODULE)/include

DIRS += $(MICRO_ROS_MODULE)/contrib/transports

ifneq (,$(filter micro_ros_time,$(USEMODULE)))
  DIRS += $(MICRO_ROS_MODULE)/contrib/time
endif

ARCHIVES += $(BINDIR)/micro_ros.a
