FEATURES_REQUIRED += cpp

USEMODULE += tsrb
USEMODULE += ztimer
USEMODULE += ztimer_msec

ifeq (,$(filter native native32 native64,$(BOARD)))
  CFLAGS += -D_POSIX_TIMERS -D_POSIX_MONOTONIC_CLOCK
  USEMODULE += posix_headers
  USEMODULE += micro_ros_time
endif

ifneq (,$(filter micro_ros_udp_transport,$(USEMODULE)))
	USEMODULE += sock_udp
	USEMODULE += netdev_default
	USEMODULE += auto_init_gnrc_netif
	USEMODULE += gnrc_ipv6_default
	# we want to be able to open one udp socket
	CFLAGS += -DCONFIG_GNRC_TCP_RCV_BUFFERS=1
endif

